/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import orçamentoDeMarketing.Imagem;

/**
 *
 * @author rodol
 */
public class UI_Imagem extends javax.swing.JFrame {

    private String dimensao;
    private int nivelDePesquisa;

    /**
     * Creates new form Imagem
     */
    public UI_Imagem() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldDimensao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        checkBoxBaixo = new javax.swing.JCheckBox();
        checkBoxMedio = new javax.swing.JCheckBox();
        checkBoxAlto = new javax.swing.JCheckBox();
        adicionarImagem = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Imagem");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IMAGEM");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(this);
        jLabel2.setText("Dimensão: 1:1, 4:5, 9:16");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        textFieldDimensao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDimensaoActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nível de Pesquisa:");

        checkBoxBaixo.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxBaixo.setText("Baixo");
        checkBoxBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBaixoActionPerformed(evt);
            }
        });

        checkBoxMedio.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxMedio.setText("Médio");
        checkBoxMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMedioActionPerformed(evt);
            }
        });

        checkBoxAlto.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxAlto.setText("Alto");
        checkBoxAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAltoActionPerformed(evt);
            }
        });

        adicionarImagem.setText("Adicionar");
        adicionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionarImagem)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkBoxBaixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxMedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxAlto))
                    .addComponent(textFieldDimensao, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDimensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxBaixo)
                    .addComponent(checkBoxMedio)
                    .addComponent(checkBoxAlto))
                .addGap(18, 18, 18)
                .addComponent(adicionarImagem)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDimensaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDimensaoActionPerformed
        dimensao = textFieldDimensao.getText();
    }//GEN-LAST:event_textFieldDimensaoActionPerformed

    private void checkBoxBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBaixoActionPerformed
        nivelDePesquisa = 1;
    }//GEN-LAST:event_checkBoxBaixoActionPerformed
    private void checkBoxAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAltoActionPerformed
        nivelDePesquisa = 3;
    }//GEN-LAST:event_checkBoxAltoActionPerformed

    private void adicionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarImagemActionPerformed
        Imagem im = new Imagem(dimensao, nivelDePesquisa);
    }//GEN-LAST:event_adicionarImagemActionPerformed

    private void checkBoxMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMedioActionPerformed
        nivelDePesquisa = 2;
    }//GEN-LAST:event_checkBoxMedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Imagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarImagem;
    private javax.swing.JCheckBox checkBoxAlto;
    private javax.swing.JCheckBox checkBoxBaixo;
    private javax.swing.JCheckBox checkBoxMedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textFieldDimensao;
    // End of variables declaration//GEN-END:variables
}
