/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orçamentoDeMarketing.UI;

/**
 *
 * @author rodol
 */
public class OpcoesUI extends javax.swing.JFrame {

    /**
     * Creates new form Opcoes
     */
    public OpcoesUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtOpcoes = new javax.swing.JLabel();
        buttonVideo = new javax.swing.JButton();
        buttonImagemFoto = new javax.swing.JButton();
        buttonTrafego = new javax.swing.JButton();
        buttonSite = new javax.swing.JButton();
        buttonPSM = new javax.swing.JButton();
        buttonAjudaPSM = new javax.swing.JButton();
        buttonAjudaTrafego1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        buttonVoltarFrame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 650));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setToolTipText("");
        jPanel3.setMinimumSize(new java.awt.Dimension(720, 720));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 650));

        txtOpcoes.setFont(new java.awt.Font("Noto Serif", 1, 48)); // NOI18N
        txtOpcoes.setForeground(new java.awt.Color(237, 125, 49));
        txtOpcoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtOpcoes.setText("OPÇÕES");

        buttonVideo.setBackground(new java.awt.Color(237, 125, 49));
        buttonVideo.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonVideo.setForeground(new java.awt.Color(255, 255, 255));
        buttonVideo.setText("VÍDEO");
        buttonVideo.setBorderPainted(false);
        buttonVideo.setFocusPainted(false);
        buttonVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVideoActionPerformed(evt);
            }
        });

        buttonImagemFoto.setBackground(new java.awt.Color(237, 125, 49));
        buttonImagemFoto.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonImagemFoto.setForeground(new java.awt.Color(255, 255, 255));
        buttonImagemFoto.setText("IMAGEM/FOTO");
        buttonImagemFoto.setBorderPainted(false);
        buttonImagemFoto.setFocusPainted(false);
        buttonImagemFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImagemFotoActionPerformed(evt);
            }
        });

        buttonTrafego.setBackground(new java.awt.Color(237, 125, 49));
        buttonTrafego.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonTrafego.setForeground(new java.awt.Color(255, 255, 255));
        buttonTrafego.setText("TRÁFEGO PAGO");
        buttonTrafego.setBorderPainted(false);
        buttonTrafego.setFocusPainted(false);
        buttonTrafego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrafegoActionPerformed(evt);
            }
        });

        buttonSite.setBackground(new java.awt.Color(237, 125, 49));
        buttonSite.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonSite.setForeground(new java.awt.Color(255, 255, 255));
        buttonSite.setText("SITE");
        buttonSite.setBorderPainted(false);
        buttonSite.setFocusPainted(false);
        buttonSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiteActionPerformed(evt);
            }
        });

        buttonPSM.setBackground(new java.awt.Color(237, 125, 49));
        buttonPSM.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonPSM.setForeground(new java.awt.Color(255, 255, 255));
        buttonPSM.setText("PACOTE SOCIAL MEDIA");
        buttonPSM.setBorderPainted(false);
        buttonPSM.setFocusPainted(false);
        buttonPSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPSMActionPerformed(evt);
            }
        });

        buttonAjudaPSM.setBackground(new java.awt.Color(237, 125, 49));
        buttonAjudaPSM.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonAjudaPSM.setForeground(new java.awt.Color(255, 255, 255));
        buttonAjudaPSM.setText("?");
        buttonAjudaPSM.setBorderPainted(false);
        buttonAjudaPSM.setFocusPainted(false);
        buttonAjudaPSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjudaPSMActionPerformed(evt);
            }
        });

        buttonAjudaTrafego1.setBackground(new java.awt.Color(237, 125, 49));
        buttonAjudaTrafego1.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonAjudaTrafego1.setForeground(new java.awt.Color(255, 255, 255));
        buttonAjudaTrafego1.setText("?");
        buttonAjudaTrafego1.setBorderPainted(false);
        buttonAjudaTrafego1.setFocusPainted(false);
        buttonAjudaTrafego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjudaTrafego1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(237, 126, 49));
        jPanel5.setForeground(new java.awt.Color(237, 126, 49));
        jPanel5.setPreferredSize(new java.awt.Dimension(97, 484));

        buttonVoltarFrame.setBackground(new java.awt.Color(51, 51, 51));
        buttonVoltarFrame.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonVoltarFrame.setForeground(new java.awt.Color(255, 255, 255));
        buttonVoltarFrame.setText("<");
        buttonVoltarFrame.setBorderPainted(false);
        buttonVoltarFrame.setFocusPainted(false);
        buttonVoltarFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(buttonVoltarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(buttonVoltarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(589, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtOpcoes))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonImagemFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSite, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonTrafego, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonPSM, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAjudaPSM, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonAjudaTrafego1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtOpcoes)
                        .addGap(91, 91, 91)
                        .addComponent(buttonImagemFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSite, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTrafego, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAjudaTrafego1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPSM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAjudaPSM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarFrameActionPerformed
        MenuPrincipalUI menu = new MenuPrincipalUI();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonVoltarFrameActionPerformed

    private void buttonAjudaTrafego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjudaTrafego1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAjudaTrafego1ActionPerformed

    private void buttonAjudaPSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjudaPSMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAjudaPSMActionPerformed

    private void buttonPSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPSMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPSMActionPerformed

    private void buttonSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSiteActionPerformed

    private void buttonTrafegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrafegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTrafegoActionPerformed

    private void buttonImagemFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImagemFotoActionPerformed
        ImagemUI im = new ImagemUI();
        im.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonImagemFotoActionPerformed

    private void buttonVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVideoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Opcoes(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcoesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjudaPSM;
    private javax.swing.JButton buttonAjudaTrafego1;
    private javax.swing.JButton buttonImagemFoto;
    private javax.swing.JButton buttonPSM;
    private javax.swing.JButton buttonSite;
    private javax.swing.JButton buttonTrafego;
    private javax.swing.JButton buttonVideo;
    private javax.swing.JButton buttonVoltarFrame;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel txtOpcoes;
    // End of variables declaration//GEN-END:variables
}
