/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package orçamentoDeMarketing.UI;

/**
 *
 * @author rodol
 */
public class Opcoes extends javax.swing.JFrame {

    /**
     * Creates new form Opcoes
     */
    public Opcoes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        buttonVoltarFrame = new javax.swing.JButton();
        txtOpcoes = new javax.swing.JLabel();
        buttonVideo = new javax.swing.JButton();
        buttonImagemFoto = new javax.swing.JButton();
        buttonTrafego = new javax.swing.JButton();
        buttonSite = new javax.swing.JButton();
        buttonPSM = new javax.swing.JButton();
        buttonAjudaPSM = new javax.swing.JButton();
        buttonAjudaTrafego1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setMinimumSize(new java.awt.Dimension(1080, 720));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setToolTipText("");
        jPanel3.setMinimumSize(new java.awt.Dimension(720, 720));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jPanel5.setBackground(new java.awt.Color(237, 126, 49));
        jPanel5.setForeground(new java.awt.Color(237, 126, 49));

        buttonVoltarFrame.setBackground(new java.awt.Color(51, 51, 51));
        buttonVoltarFrame.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonVoltarFrame.setForeground(new java.awt.Color(255, 255, 255));
        buttonVoltarFrame.setText("<");
        buttonVoltarFrame.setBorderPainted(false);
        buttonVoltarFrame.setFocusPainted(false);
        buttonVoltarFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(buttonVoltarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(buttonVoltarFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 339, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtOpcoes.setFont(new java.awt.Font("Noto Serif", 1, 48)); // NOI18N
        txtOpcoes.setForeground(new java.awt.Color(237, 125, 49));
        txtOpcoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtOpcoes.setText("OPÇÕES");

        buttonVideo.setBackground(new java.awt.Color(237, 125, 49));
        buttonVideo.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonVideo.setForeground(new java.awt.Color(255, 255, 255));
        buttonVideo.setText("VÍDEO");
        buttonVideo.setBorderPainted(false);
        buttonVideo.setFocusPainted(false);
        buttonVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVideoActionPerformed(evt);
            }
        });

        buttonImagemFoto.setBackground(new java.awt.Color(237, 125, 49));
        buttonImagemFoto.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonImagemFoto.setForeground(new java.awt.Color(255, 255, 255));
        buttonImagemFoto.setText("IMAGEM/FOTO");
        buttonImagemFoto.setBorderPainted(false);
        buttonImagemFoto.setFocusPainted(false);
        buttonImagemFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImagemFotoActionPerformed(evt);
            }
        });

        buttonTrafego.setBackground(new java.awt.Color(237, 125, 49));
        buttonTrafego.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonTrafego.setForeground(new java.awt.Color(255, 255, 255));
        buttonTrafego.setText("TRÁFEGO PAGO");
        buttonTrafego.setBorderPainted(false);
        buttonTrafego.setFocusPainted(false);
        buttonTrafego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTrafegoActionPerformed(evt);
            }
        });

        buttonSite.setBackground(new java.awt.Color(237, 125, 49));
        buttonSite.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonSite.setForeground(new java.awt.Color(255, 255, 255));
        buttonSite.setText("SITE");
        buttonSite.setBorderPainted(false);
        buttonSite.setFocusPainted(false);
        buttonSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiteActionPerformed(evt);
            }
        });

        buttonPSM.setBackground(new java.awt.Color(237, 125, 49));
        buttonPSM.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonPSM.setForeground(new java.awt.Color(255, 255, 255));
        buttonPSM.setText("PACOTE SOCIAL MEDIA");
        buttonPSM.setBorderPainted(false);
        buttonPSM.setFocusPainted(false);
        buttonPSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPSMActionPerformed(evt);
            }
        });

        buttonAjudaPSM.setBackground(new java.awt.Color(237, 125, 49));
        buttonAjudaPSM.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonAjudaPSM.setForeground(new java.awt.Color(255, 255, 255));
        buttonAjudaPSM.setText("?");
        buttonAjudaPSM.setBorderPainted(false);
        buttonAjudaPSM.setFocusPainted(false);
        buttonAjudaPSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjudaPSMActionPerformed(evt);
            }
        });

        buttonAjudaTrafego1.setBackground(new java.awt.Color(237, 125, 49));
        buttonAjudaTrafego1.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        buttonAjudaTrafego1.setForeground(new java.awt.Color(255, 255, 255));
        buttonAjudaTrafego1.setText("?");
        buttonAjudaTrafego1.setBorderPainted(false);
        buttonAjudaTrafego1.setFocusPainted(false);
        buttonAjudaTrafego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjudaTrafego1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonImagemFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonSite, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonTrafego, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonPSM, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonAjudaPSM, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonAjudaTrafego1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtOpcoes)
                        .addGap(106, 106, 106)))
                .addGap(96, 96, 96))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(txtOpcoes)
                .addGap(47, 47, 47)
                .addComponent(buttonImagemFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSite, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTrafego, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAjudaTrafego1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPSM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAjudaPSM, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarFrameActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonVoltarFrameActionPerformed

    private void buttonVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVideoActionPerformed

    private void buttonImagemFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImagemFotoActionPerformed
        Imagem im = new Imagem();
        im.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonImagemFotoActionPerformed

    private void buttonTrafegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTrafegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTrafegoActionPerformed

    private void buttonSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSiteActionPerformed

    private void buttonPSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPSMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPSMActionPerformed

    private void buttonAjudaPSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjudaPSMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAjudaPSMActionPerformed

    private void buttonAjudaTrafego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjudaTrafego1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAjudaTrafego1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void Opcoes(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjudaPSM;
    private javax.swing.JButton buttonAjudaTrafego1;
    private javax.swing.JButton buttonImagemFoto;
    private javax.swing.JButton buttonPSM;
    private javax.swing.JButton buttonSite;
    private javax.swing.JButton buttonTrafego;
    private javax.swing.JButton buttonVideo;
    private javax.swing.JButton buttonVoltarFrame;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel txtOpcoes;
    // End of variables declaration//GEN-END:variables
}
